name: CI Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . 
          file: ./Dockerfile  
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/llm-inference-image:latest  

      - name: Run tests
        run: |
          docker run -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/llm-inference-image:latest  
          sleep 10  
          curl -X POST -H "Content-Type: application/json" -d '{"text": "This is a test"}' http://localhost:5000/infer  
