name: CI Pipeline

on:
  push:
    branches:
      - main  # هر بار که به شاخه main push می‌کنی، اجرا می‌شه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: YOUR_USERNAME/llm-inference-image:latest  # YOUR_USERNAME رو عوض کن

      - name: Run tests
        run: |
          docker run --rm YOUR_USERNAME/llm-inference-image:latest python app.py &
          sleep 10
          curl -X POST http://localhost:5000 -d "text=Test"
